[tool.black]
line-length = 120
target-version = ['py38']

[tool.isort]
force_single_line = true
default_section = "THIRDPARTY"
include_trailing_comma = true
line_length = 120
not_skip = "__init__.py"
