# Generated by Django 3.1.7 on 2021-03-03 13:49

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=128, verbose_name="название")),
                ("started_at", models.DateTimeField(verbose_name="время начала игры")),
                ("hint_penalty", models.IntegerField(verbose_name="штраф за подсказку (в секундах)")),
                ("mistake_penalty", models.IntegerField(verbose_name="штраф за ошибку (в секундах)")),
            ],
            options={
                "verbose_name": "игра",
                "verbose_name_plural": "игры",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(max_length=1024, verbose_name="текст")),
                ("correct_answer", models.TextField(max_length=256, verbose_name="правильный ответ")),
                ("longitude", models.FloatField(verbose_name="долгота")),
                ("latitude", models.FloatField(verbose_name="широта")),
                (
                    "quiz",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="quiz.quiz", verbose_name="игра"),
                ),
            ],
            options={
                "verbose_name": "вопрос",
                "verbose_name_plural": "вопросы",
            },
        ),
        migrations.CreateModel(
            name="Hint",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(max_length=1024, verbose_name="текст")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.question", verbose_name="вопрос"
                    ),
                ),
            ],
            options={
                "verbose_name": "подсказка",
                "verbose_name_plural": "подсказки",
            },
        ),
        migrations.CreateModel(
            name="GivenHint",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group", verbose_name="команда"
                    ),
                ),
                (
                    "hint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.hint", verbose_name="подсказка"
                    ),
                ),
            ],
            options={
                "verbose_name": "данная подсказка",
                "verbose_name_plural": "данные подсказки",
                "unique_together": {("group", "hint")},
            },
        ),
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(max_length=1024, verbose_name="текст")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="дата создания")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group", verbose_name="команда"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.question", verbose_name="вопрос"
                    ),
                ),
            ],
            options={
                "verbose_name": "ответ на вопрос",
                "verbose_name_plural": "ответы на вопросы",
            },
        ),
    ]
